// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID            int64
	Name          string
	LastUpdatedAt sql.NullString
	Url           string
	FeedType      sql.NullString
}

type Post struct {
	ID          int64
	Title       string
	Url         string
	PublishedAt string
	FeedID      int64
}
