// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :exec
insert into
  feed (name, url, feed_type)
values
  (?, ?, ?)
`

type CreateFeedParams struct {
	Name     string
	Url      string
	FeedType string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.ExecContext(ctx, createFeed, arg.Name, arg.Url, arg.FeedType)
	return err
}

const createPost = `-- name: CreatePost :exec
insert or ignore into
  post (title, url, published_at, feed_id)
values
  (?, ?, ?, ?)
`

type CreatePostParams struct {
	Title       string
	Url         string
	PublishedAt string
	FeedID      int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Url,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const deleteFeed = `-- name: DeleteFeed :exec
delete from feed
where
  id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
delete from post
where
  id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const listFeeds = `-- name: ListFeeds :many
select
  id, name, last_updated_at, url, feed_type, date_format
from
  feed
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUpdatedAt,
			&i.Url,
			&i.FeedType,
			&i.DateFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPost = `-- name: ListPost :many
select
  id, title, url, published_at, feed_id
from
  post
`

func (q *Queries) ListPost(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithFeed = `-- name: ListPostsWithFeed :many
select
  p.id,
  p.title,
  p.url,
  p.published_at,
  p.feed_id,
  f.name as feed_name
from
  post p
  inner join feed f on p.feed_id = f.id
order by
  p.published_at desc
`

type ListPostsWithFeedRow struct {
	ID          int64
	Title       string
	Url         string
	PublishedAt string
	FeedID      int64
	FeedName    string
}

func (q *Queries) ListPostsWithFeed(ctx context.Context) ([]ListPostsWithFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsWithFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsWithFeedRow
	for rows.Next() {
		var i ListPostsWithFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedDate = `-- name: UpdateFeedDate :exec
update feed
set
  last_updated_at = ?
where
  id = ?
`

type UpdateFeedDateParams struct {
	LastUpdatedAt sql.NullString
	ID            int64
}

func (q *Queries) UpdateFeedDate(ctx context.Context, arg UpdateFeedDateParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedDate, arg.LastUpdatedAt, arg.ID)
	return err
}

const updateFeedFormat = `-- name: UpdateFeedFormat :exec
update feed
set
  date_format = ?
where
  id = ?
`

type UpdateFeedFormatParams struct {
	DateFormat sql.NullString
	ID         int64
}

func (q *Queries) UpdateFeedFormat(ctx context.Context, arg UpdateFeedFormatParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedFormat, arg.DateFormat, arg.ID)
	return err
}
